services:
  redis:
    image: redis:latest
    container_name: redis
    restart: on-failure
    ports:
      - '6380:6380'
    environment:
      - REDIS_PASSWORD=mysecretpassword
    command: /bin/sh -c "redis-server --port 6380 --save 20 1 --loglevel warning --requirepass $$REDIS_PASSWORD"
    volumes:
      - redis:/data
    networks:
      - chatbot_network

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: data_app
      POSTGRES_PASSWORD: data12345 # pragma: allowlist secret
      POSTGRES_DB: datadb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/01_demokitsune_demo_30062025.sql:/docker-entrypoint-initdb.d/01_demokitsune_demo_30062025.sql
      - ./postgres/02_function_total_gross_premium.sql:/docker-entrypoint-initdb.d/02_function_total_gross_premium.sql
      - ./postgres/03_function_get_last_endorsements_id.sql:/docker-entrypoint-initdb.d/03_function_get_last_endorsements_id.sql
      - ./postgres/04_function_get_premiums.sql:/docker-entrypoint-initdb.d/04_function_get_premiums.sql
    networks:
      - chatbot_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password # pragma: allowlist secret
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - chatbot_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password # pragma: allowlist secret
      ME_CONFIG_MONGODB_URL: mongodb://user:password@mongodb:27017/ # pragma: allowlist secret
    networks:
      - chatbot_network
    depends_on:
      - mongodb

  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GUARDRAILS_HUB_TOKEN=${GUARDRAILS_HUB_TOKEN:-}
    container_name: chatbot_service
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/server_app/application_default_credentials.json
    volumes:
      - lancedb_data:/server_app/lancedb
      - ${GCP_CREDENTIALS}:/server_app/application_default_credentials.json
    networks:
      - chatbot_network
    depends_on:
      - redis
      - postgres
      - mongodb

volumes:
  redis:
    driver: local
  mongodb_data:
    driver: local
  lancedb_data:
    driver: local

networks:
  chatbot_network:
    driver: bridge
