#!/bin/bash

# List of environment variables to unset
env_vars=(
    AZURE_OPENAI_API_KEY
    AZURE_OPENAI_API_ENDPOINT
    AZURE_OPENAI_LLM_DEPLOYMENT_NAME
    AZURE_OPENAI_API_VERSION
    AZURE_OPENAI_LLM_MODEL
    AZURE_OPENAI_EMBEDDING_MODEL
    AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME
    REDIS_ENABLE_FLAG
    REDIS_HOST
    REDIS_PORT
    REDIS_PASSWORD
    REDIS_DB
    LANCEDB_PATH
    LANCEDB_TABLE_NAME
    LANCEDB_EMBEDDING_MODEL
    POSTGRES_HOST
    POSTGRES_PORT
    POSTGRES_DB
    POSTGRES_USER
    POSTGRES_PASSWORD
    POSTGRES_SCHEMA
    ALLOWED_TOPICS
    AZURE_OPENAI_ENDPOINT
    AZURE_OPENAI_LLM_TESTING_DEPLOYMENT_NAME
)

# Unset each variable in the list
for var in "${env_vars[@]}"; do
    unset $var
done

echo "All specified environment variables have been unset."
