apiVersion: v1
kind: Secret
metadata:
  name: chatbot
  namespace: cbot
stringData:
  redis-password: "S5Wn9VaEWH"
  azure_openai_api_key: "" #sensitive
  aws-region: ""
  aws-access-key-id: ""
  aws-secret-access-key: ""
  aws-session-token: ""
  postgres-password: "securepassword"
  mongodb-password: ""
type: Opaque