apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: inari-henzuru-data
  namespace: argo
spec:
  revisionHistoryLimit: 3
  template:
    serviceAccountName: operate-workflow-sa
    nodeSelector:
      cloud.google.com/gke-spot: "true"
  dependencies:
  - name: inari-henzuru-data
    eventSourceName: github
    eventName: github
    filters:
      dataLogicalOperator: "and"
      data:
      - path: body.repository.name
        type: string
        value:
        - inari-henzuru-data
      - path: body.ref
        type: string
        value:
        - refs/heads/master
      - path: headers.X-Github-Event
        type: string
        value:
        - push
  triggers:
  - template:
      name: inari-henzuru-data
      k8s:
        operation: create
        parameters:
        - src:
            dependencyName: inari-henzuru-data
            dataTemplate: "{{.Input.body.repository.ssh_url }}"
          dest: spec.arguments.parameters.0.value
        - src:
            dependencyName: inari-henzuru-data
            dataTemplate: "{{.Input.body.repository.name }}"
          dest: spec.arguments.parameters.1.value
        - src:
            dependencyName: inari-henzuru-data
            dataTemplate: '{{.Input.body.ref | trimPrefix "refs/heads/" }}'
          dest: spec.arguments.parameters.2.value
        - src:
            dependencyName: inari-henzuru-data
            dataTemplate: harbor.tech.inari.io/data/{{.Input.body.repository.name}}
          dest: spec.arguments.parameters.3.value
        - src:
            dependencyName: inari-henzuru-data
            dataTemplate: '-{{.Input.body.ref | trimPrefix "refs/heads/" }}-{{.Input.body.head_commit.id | substr 0 7}}'
          dest: metadata.name
          operation: append
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              name: inari-henzuru-data
            spec:
              activeDeadlineSeconds: 28800
              ttlStrategy:
                secondsAfterCompletion: 86400
              serviceAccountName: operate-workflow-sa
              entrypoint: main
              arguments:
                parameters:
                - name: repo
                - name: path
                - name: revision
                - name: image
              templates:
              - name: main
                dag:
                  tasks:
                  - name: version-from-file
                    templateRef:
                      name: inputs-outputs
                      template: version-from-file
                    arguments:
                      parameters:
                        - name: repo
                          value: "{{workflow.parameters.repo}}"
                        - name: path
                          value: "{{workflow.parameters.path}}"
                        - name: revision
                          value: "{{workflow.parameters.revision}}"
                        - name: command
                          value: 'cat pyproject.toml | grep ''"version":''| awk ''{print $2}'' | sed ''s/"//g; s/,//g'' > /tmp/tag'

                  - name: container-image
                    depends: "version-from-file"
                    templateRef:
                      name: container-image
                      template: container-image-gcp-buildkit
                    arguments:
                      parameters:
                        - name: repo
                          value: "{{workflow.parameters.repo}}"
                        - name: path
                          value: "{{workflow.parameters.path}}"
                        - name: revision
                          value: "{{workflow.parameters.revision}}"
                        - name: image
                          value: "{{workflow.parameters.image}}"
                        - name: imagefile-folder
                          value: "."
                        - name: imagefile-path
                          value: "."
                        - name: tag
                          value: "{{tasks.version-from-file.outputs.parameters.tag}}"
                        - name: gcp-token
                          value: "not-needed"